platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: latest

inputs:
  - name: REvaluation-UI
  - name: dependency-cache

run:
  path: REvaluation-UI/ci/scripts/run_tests.sh
