resource_types:
  - name: npm-cache
    type: docker-image
    source:
      repository: REvaluation-UI/npm-cache-resource
      tag: latest
resources:
  - name: REvaluation-UI
    type: git
    source: &repo-source
      uri: https://github.homedepot.com/checkout-intern/REvaluation-UI
      branch: master
  - name: dependency-cache
    type: npm-cache
    source:
      <<: *repo-source
      paths:
        - package.json
jobs:
  - name: Install dependencies
    plan:
      - get: REvaluation-UI
        trigger: true
      - get: dependency-cache
  - name: Run tests
    plan:
      - get: REvaluation-UI
        trigger: true
        passed: [Install dependencies]
      - get: dependency-cache
        passed: [Install dependencies]
      - task: run the test suite
        file: REvaluation-UI/ci/tasks/run_tests.yml

